//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eoExpedientesEntities : DbContext
    {
        public eoExpedientesEntities()
            : base("name=eoExpedientesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ambiente_abt> ambiente_abt { get; set; }
        public virtual DbSet<caja_cja> caja_cja { get; set; }
        public virtual DbSet<ciudad_cdd> ciudad_cdd { get; set; }
        public virtual DbSet<estado_edo> estado_edo { get; set; }
        public virtual DbSet<expediente_ambiente_ea> expediente_ambiente_ea { get; set; }
        public virtual DbSet<expediente_aval_ea> expediente_aval_ea { get; set; }
        public virtual DbSet<expediente_demandado_ed> expediente_demandado_ed { get; set; }
        public virtual DbSet<expediente_estado_ee> expediente_estado_ee { get; set; }
        public virtual DbSet<expediente_exp> expediente_exp { get; set; }
        public virtual DbSet<juzgado_jdo> juzgado_jdo { get; set; }
        public virtual DbSet<materia_mra> materia_mra { get; set; }
        public virtual DbSet<personal_prl> personal_prl { get; set; }
        public virtual DbSet<registro_rto> registro_rto { get; set; }
        public virtual DbSet<sesion_ssn> sesion_ssn { get; set; }
        public virtual DbSet<tipo_tpo> tipo_tpo { get; set; }
    }
}
