//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_rto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registro_rto()
        {
            this.caja_cja = new HashSet<caja_cja>();
            this.expediente_aval_ea = new HashSet<expediente_aval_ea>();
            this.expediente_demandado_ed = new HashSet<expediente_demandado_ed>();
            this.expediente_exp = new HashSet<expediente_exp>();
        }
    
        public int rto_id { get; set; }
        public string rto_apellidos { get; set; }
        public string rto_nombres { get; set; }
        public string rto_color { get; set; }
        public int tpo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja_cja> caja_cja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expediente_aval_ea> expediente_aval_ea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expediente_demandado_ed> expediente_demandado_ed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expediente_exp> expediente_exp { get; set; }
        public virtual tipo_tpo tipo_tpo { get; set; }
    }
}
